config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'theory_points/new'
  end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :admin do 
    get 'login', to: "sessions#new", as: "login"
    post 'login', to: "sessions#create"
    delete 'logout', to: "sessions#destroy", as: "logout"

    resources :subjects, shallow: true, only: [:index, :create], param: "slug" do
        resources :lessons, only: [:create, :index, :edit, :destroy, :update, :show], param: "lesson_slug" do
        end
        resources :lessons, param: "slug" do 
            get "index_show" # to 'lessons#index_show' action.
        end
    end

    resources :subjects, only: [:update, :destroy, :edit], param: "subject_slug"

    resources :lessons, param: "slug", only: [] do 
      resources :lesson_pages, only: [:show, :edit, :update, :destroy, :create], param: "lesson_page_id", shallow: true
      resource :problem, only: [:show, :edit, :update], param: "problem_id"
      resource :summary, only: [:show, :edit, :update], param: "problem_id"
    end

    resources :lesson_pages, only: [], shallow: true do
      resources :theory_points, only: [:new, :create, :destroy], shallow: true
    end

    resources :summaries, only: [] do
      resources :alternatives, only: [:new, :create, :edit, :update, :show, :destroy]
    end
  end
  # Defines the root path route ("/")
  root to: "subjects#index" 
  get '/about', to: "pages#about", as: "about"
  get '/recruiters', to: "pages#recruiters", as: "recruiters"

  get '/:subject_slug/lessons', to: "lessons#index_by_subject", as: 'lessons' 
  get '/lesson/:lesson_slug', to: "lessons#show", as: 'lesson'
  get '/lesson/:lesson_slug/problem', to: "problem#show", as: 'problem'
  get '/lesson/:lesson_slug/part-(:lesson_page_id)', to: "lesson_pages#show", as: 'lesson_page'
  get '/lesson/:lesson_slug/summary', to: "summary#show", as: 'summary'
end

app/models/alternative.rb
class Alternative < ApplicationRecord
  belongs_to :summary, counter_cache: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_secure_password

  has_many :subjects
end

app/models/device_user.rb
class DeviceUser < ApplicationRecord
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  after_create :createInitialPages
  after_create :addIdToSubject

  after_destroy :removeIdFromSubject

  belongs_to :subject

  has_one :problem, dependent: :destroy
  has_one :summary, dependent: :destroy

  has_one_attached :image

  has_many :lesson_pages, dependent: :destroy

  def to_param
    return nil unless persisted?
    self.title.downcase.gsub(' ', '-') # 1-english-for-everyone
  end

  def createInitialPages
      self.create_problem!(title: "Untitled Problem")
      self.create_summary!(aftermath: "Empty Aftermath Description")
      page = self.lesson_pages.create!(title: "Untitled Page")
      self.update!(page_id_order: [page.id])
  end

  def addIdToSubject
      self.subject.addLessonId(self.id)
  end

  def removeIdFromSubject
      self.subject.removeLessonId(self.id)
  end
end

app/models/lesson_objective.rb
class LessonObjective < ApplicationRecord
  belongs_to :lesson
end

app/models/lesson_page.rb
class LessonPage < ApplicationRecord
  belongs_to :lesson, counter_cache: true

  has_many :theory_points
  accepts_nested_attributes_for :theory_points

end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :lesson

  has_one_attached :image
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :summary
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :creator
    has_many :lessons

    has_one_attached :image

    def to_param
        return nil unless persisted?
        self.title.downcase.gsub(' ', '-') # 1-english-for-everyone
    end

    def addLessonId(num)
        new_order = self.lesson_id_order.unshift(num)
        self.update!(lesson_id_order: new_order)
    end

    def removeLessonId(num)
        new_order = self.lesson_id_order - [num]
        self.update(lesson_id_order: new_order)
    end
end

app/models/summary.rb
class Summary < ApplicationRecord
  has_many :alternatives

  has_one_attached :aftermath_image
  has_one_attached :process_diagram

  belongs_to :lesson
end

app/models/theory_point.rb
class TheoryPoint < ApplicationRecord
  belongs_to :lesson_page

  has_one_attached :image
end

app/controllers/admin/summaries_controller.rb
class Admin::SummariesController < ApplicationController
  layout "admin"

  def show
      @lesson = Lesson.find_by(title: lesson_title_param)
      @subject = @lesson.subject

      @lesson_pages = LessonPage.find(@lesson.page_id_order)
      @summary = @lesson.summary
      @aftermath_image = @summary.aftermath_image
      @process_diagram = @summary.process_diagram

      @last_lesson_page = LessonPage.find(@lesson.page_id_order[-1])
      @summary_alternatives = @summary.alternatives
  end

  def edit
      @lesson = Lesson.find_by(title: lesson_title_param)

      @summary = @lesson.summary
      @aftermath_image = @summary.aftermath_image
      @process_diagram = @summary.process_diagram
      @summary_alternatives = @summary.alternatives
  end

  def update
      @lesson = Lesson.find_by(title: lesson_title_param)
      @subject = @lesson.subject

      @lesson_pages = @lesson.lesson_pages
      @summary = @lesson.summary

      @summary.update!(summary_params)

      flash[:notice] = 'Summary updated successfully'
      redirect_to admin_lesson_summary_path(@lesson)
  end

  private 

  def lesson_params
      params.require(:lesson).permit(:title, :subtitle, :description, :image, :objectives)
  end

  def subject_title_param
      params[:subject_slug]&.gsub("-", " ")&.capitalize
  end

  def lesson_title_param
      params[:lesson_slug]&.gsub("-", " ")&.capitalize
  end  

  def problem_params
      params.require(:summary).permit(:sources)
  end

  def summary_params
      sum_params = params.require(:summary).permit(:aftermath, :key_points, :sources, :process_diagram, :aftermath_image)
      sum_params[:key_points] = sum_params[:key_points].present? ? JSON.parse(sum_params[:key_points]) : ''
      sum_params[:sources] = sum_params[:sources].present? ? JSON.parse(sum_params[:sources]) : ''
      return sum_params
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def show
    @lesson = Lesson.find_by(title: lesson_title_param)
    @subject = @lesson.subject
    @problem = @lesson.problem

    subject_lesson_order = @subject.lesson_id_order

    lesson_index = subject_lesson_order.index(@lesson.id)
    next_lesson_id = subject_lesson_order[lesson_index + 1]
    @next_lesson = next_lesson_id.nil? ? nil : Lesson.find(next_lesson_id)
    
    @lesson_pages = LessonPage.find(@lesson.page_id_order)

    @summary = @lesson.summary
    @aftermath_image = @summary.aftermath_image
    @process_diagram = @summary.process_diagram

    @summary_alternatives = @summary.alternatives
    @last_page_index = @lesson.lesson_pages_count

    @current_page = "summary"
  end

  private
  
  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :objectives, :process_diagram, :pros, :cons)
  end

  def subject_title_param
    params[:subject_slug]&.gsub("-", " ")&.capitalize
  end

  def lesson_title_param
    params[:lesson_slug]&.gsub("-", " ")&.capitalize
  end  
end

app/helpers/admin/summaries_helper.rb
module Admin::SummariesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_users_helper.rb
module DeviceUsersHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/admin/summaries/_page_list.html.erb
<div class="flex flex-col flex-nowrap items-end overflow-y-scroll flex-1" id="lesson_pages_list">
    <%= link_to "Problem", admin_lesson_problem_path(lesson), class:"mb-3 w-[15rem] unselected lesson_page_button flex-0 
                            group rounded px-6 py-2 shadow-md flex text-xl font-semibold " %>
    <% lesson_pages.each do |lesson_page| %>
            <%= link_to admin_lesson_page_path(lesson_page), class: "mb-3 w-[15rem] unselected lesson_page_button flex-0 group rounded px-6 py-2 shadow-md flex items-center flex-col h-fit", data: { turbo_frame: "show_lesson" } do %>
                        <div class="w-full flex justify-between items-center">
                            <span class="text-xl font-semibold group-hover:underline flex-1">
                                <%= lesson_page.title.capitalize %>
                            </span>
                        </div>
            <% end %>
    <% end %>
    <div class="mb-3 selected lesson_page_button w-[15rem] flex-0 group rounded px-6 py-2 shadow-md flex text-xl font-semibold">
        Summary
    </div>
</div>

app/views/admin/summaries/edit.html.erb
<!--
<%= turbo_frame_tag "edit_summary_page" do %>
    <%= form_with(model: @summary, scope: :summary, method: :patch, url: admin_lesson_summary_path(@lesson), 
        data: { 'admin-target': "editLessonSummaryForm" } ) do |f| %>
        <div class="title py-6 text-center text-4xl bg-slate-200">
        <div class="py-6">Summary</div>
        </div>
        <div class="bg-[#F7FCFC] flex md:flex-row flex-col p-6">
            <label for="aftermath_image_uploads" class="flex-1 flex flex-col justify-center hover:cursor-pointer">
                <% if @aftermath_image.representable? %>
                        <%= image_tag(@aftermath_image.representation(resize_to_limit: [300, 300]), data: { 'admin-target':'imageBox' },
                        class: "object-fill flex-1 w-1/2 p-8") %>
                <% else %>
                    <%= image_tag(image_path('upload_image.png'), class: "object-fill",  data: { 'admin-target':'imageBox' }) %>
                <% end %>
                <%= f.file_field :aftermath_image, type: "file", id: "aftermath_image_uploads", accept: ".png, .jpeq, .jpg, .webP", 
                        class: "image_fill hidden", data: { 'action': 'change->admin#display_image', 'admin-target':'imageInput' } %>
            </label>
            <div class="flex-1 px-4 flex flex-col justify-between align-center">
                <div class="text-xl text-center pb-4">Aftermath:</div>
                <%= f.text_area :aftermath, class: "p-2 text-lg flex-1 text-center" %>
            </div>
        </div>
        <div class="bg-white flex flex-col md:flex-row">
            <div class="p-6 flex flex-col items-center flex-1 justify-between">
                <div class="flex flex-col w-full">
                    <div class="text-2xl text-center pt-4">
                        Key Points:
                    </div>
                    <ul class="pt-6 list-disc text-lg text-center w-full key-points" data-admin-target="summaryKeyPointsInput">
                        <% if (@summary.key_points.count == 0) %>
                                <%= f.hidden_field :key_points, value: '[]' %>
                                <li class="mb-1"><input class="summary_source border-none w-[95%]" type="text" name="summary[key_point]" value="" ></li>
                        <% else %>
                            <%= f.hidden_field :key_points, value: @summary.key_points.to_json %>
                            <% @summary.key_points.each do |key_point| %>
                                <li class="mb-1">
                                    <input class="summary_source border-none w-fit w-max-[95%]" type="text" name="summary[key_point]" value="<%= key_point.capitalize %>" >
                                    <span class="cross" data-action="click->admin#remove_bullet">&#9587;</span>
                                </li>
                            <% end %>
                        <% end %>
                    </ul>
                </div>
                <div class="flex flex-col w-full">
                        <%= f.text_area :key_point, class: "max-h-[4.5rem] flex summary_key_point flex-1 pl-4 w-full
                            border border-solid focus:border-blue-900 rounded", data: { "admin-target":"newSummaryKeyPoint" }, rows: 3 %>
                        <div class="flex self-end">
                            <div data-action="click->admin#update_summary_key_points" class="w-fit btn-blue text-sm
                                    font-light px-4 py-2 border-black text-md rounded mt-4 hover:cursor-pointer align-end">
                                Update Key Points
                            </div>
                            <div data-action="click->admin#add_summary_key_point" class="h-fit ml-2 w-fit btn-blue text-sm
                                    font-light px-4 py-2 border-black text-md rounded mt-4 hover:cursor-pointer">
                                + Add Key Point
                            </div>
                        </div>
                </div>
            </div>
            <div class="p-6 flex flex-col items-center flex-1 bg-[beige]">
                    <div class="text-2xl text-center py-4">
                        Process Diagram:
                    </div>
                    <label for="process_diagram_uploads" class="flex-1 flex flex-col justify-center hover:cursor-pointer">
                        <% if @process_diagram.representable? %>
                                <%= image_tag(@process_diagram.representation(resize_to_limit: [300, 300]), data: { 'admin-target':'imageBox2' },
                                class: "flex-1 border border-black border-4 object-fill my-4") %>
                        <% else %>
                                <%= image_tag(image_path('upload_image.png'), class: "object-contain",  data: { 'admin-target':'imageBox2' }) %>
                        <% end %>
                        <%= f.file_field :process_diagram, type: "file", id: "process_diagram_uploads", accept: ".png, .jpeq, .jpg, .webP", 
                                class: "image_fill hidden", data: { 'action': 'change->admin#display_image2', 'admin-target':'imageInput2' } %>
                    </label>
            </div>
        </div>
        <div class="bg-[#F7FCFC] pt-4">
            <div class="text-2xl justify-center py-6 flex">
                <span class="mr-4">Money and Time saved:</span>
                <%= link_to "New Alternative", new_admin_summary_alternative_path(@summary), 
                    data: { turbo_frame: "new_alternative" }, class: "btn btn-blue border-black text-sm font-light rounded" %>
            </div>
            <div class="mx-10 px-6 pb-6 flex flex-col items-center justify-center">
                <% if (@summary.alternatives_count > 0) %>
                    <% @summary_alternatives.each do |alternative| %>
                            <div class="flex mx-6 mb-6 items-center border border-slate-300 rounded bg-white w-full">
                                <div class="flex flex-col p-4 items-center"> 
                                    <span class="text-lg font-semibold pb-2"><%= alternative.title %></span>
                                    <span>Money Saved: $<%= alternative.money_saved %></span>
                                    <span>Time (hours) saved: <%= alternative.time_saved %></span>
                                    <span>Use cases:</span>
                                    <span><%= alternative.use_case %></span>
                                    <%= link_to 'Delete', admin_summary_alternative_path(@summary, alternative), data: {turbo_method: :delete, turbo_confirm: "are you sure?"}, 
                                        class: "bg-gray-200 hover:bg-gray-300 text-gray-700 px-4 py-2 border-black bg-slate-grey text-md rounded" %>
                                </div>     
                                <div class="flex pl-4 self-start flex-1">
                                    <div class="flex-col flex flex-1 mr-4">
                                        <span class="py-4">Pros:</span>
                                        <span><%= alternative.pros %></span>
                                    </div>
                                    <div class="flex-col flex flex-1 mr-4">
                                        <span class="py-4">Cons:</span>
                                        <span><%= alternative.pros %></span>
                                    </div>
                                </div>
                            </div>                  
                    <% end %>
                <% end %>
                <%= turbo_frame_tag "new_alternative", target: "_top" %>           
            </div>
        </div>  
        <hr class="border-slate-400 bg-slate-400">
        <div class="bg-[#F7FCFC]">
            <div class="mx-10 p-6 flex flex-col items-center list-holder">
                <div class="text-2xl text-center pt-4">
                    Further Reading:
                </div>
                <div class="flex flex-col w-full">
                    <div class="text-2xl text-center pt-4">
                        Key Points:
                    </div>
                    <ul class="py-6 list-disc text-lg text-center w-full key-points" data-admin-target="summarySourcesInput">
                        <% if (@summary.sources.count == 0) %>
                                <%= f.hidden_field :sources, value: '[]' %>
                                <li class="mb-1"><input class="summary_source border-none w-[95%] bg-transparent" type="text" name="summary[source]" value="" ></li>
                        <% else %>
                            <%= f.hidden_field :sources, value: @summary.sources.to_json %>
                            <% @summary.sources.each do |source| %>
                                <li class="mb-1">
                                    <input class="summary_source border-none w-[95%] bg-transparent" type="text" name="summary[source]" value="<%= source.capitalize %>" >
                                    <span class="cross" data-action="click->admin#remove_bullet">&#9587;</span>
                                </li>
                            <% end %>
                        <% end %>
                    </ul>
                </div>
                <div class="flex flex-col w-full">
                    <%= f.text_area :source, value: "", class: "max-h-[4.5rem] flex summary_source flex-1 pl-4 w-full
                        border border-solid focus:border-blue-900 rounded", data: { "admin-target":"newSummarySource" }, rows: 3 %>
                    <div class="flex self-end">
                        <div data-action="click->admin#update_summary_sources" class="w-fit btn-blue text-sm
                                font-light px-4 py-2 border-black text-md rounded mt-4 hover:cursor-pointer align-end">
                            Update Sources
                        </div>
                        <div data-action="click->admin#add_summary_source" class="h-fit ml-2 w-fit btn-blue text-sm
                                font-light px-4 py-2 border-black text-md rounded mt-4 hover:cursor-pointer">
                            + Add Sources
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>
    -->

app/views/summary/show.html.erb
<nav class="sticky top-0 flex justify-between bg-zinc-100 items-center" data-controller="lesson-nav">
    <div class="md:static relative w-full flex justify-between">
        <%= link_to "< Prev", lesson_page_path(@lesson, @last_page_index),
        class:"hover:bg-sky-100 px-4 py-2 md:py-4 flex-0 border-black bg-slate-grey md:text-2xl text-xl font-light rounded" %>
        <div data-action="click->lesson-nav#toggle_page_list" class="static md:relative flex-1 flex justify-center md:max-w-[30rem]">
            <div class="justify-center  items-center h-full hover:cursor-pointer hover:bg-sky-100 flex flex-1">
                <%= image_tag(image_path('page_list.png'), class: "object-fill pr-2") %>
                <span class="text-xl hidden sm:inline"><%= @lesson.title %></span>
            </div>
            <%= render partial: "shared/page_list", locals: { lesson: @lesson, subject: @subject, lesson_pages: @lesson_pages, 
                        problem: @problem, summary: @summary, current_page: @current_page } %>
        </div>
        <% if @next_lesson.present? %>
            <%= link_to "Next >", problem_path(@next_lesson),
            class:"hover:bg-sky-100 px-4 py-2 md:py-4 flex-0 border-black bg-slate-grey md:text-2xl text-xl font-light rounded" %>
        <% else %>
            <%= link_to "Home", root_path,
            class:"hover:bg-sky-100 px-4 py-2 md:py-4 flex-0 border-black bg-slate-grey md:text-2xl text-xl font-light rounded" %>
        <% end %>
    </div>
</nav>
<div class="title py-6 text-center text-2xl md:text-4xl bg-slate-200">
    <div class="md:py-6">Summary</div>
</div>
<div class="bg-[#F7FCFC] flex md:flex-row flex-col pb-6">
    <div class="flex flex-col md:px-10 mb-4 md:flex-row pt-6 md:pt-10">
        <div class="mx-10 flex flex-col items-center">
            <figure class="max-w-[35vw]">
                <% if @aftermath_image.representable? %>
                    <%= image_tag @aftermath_image.representation(resize_to_limit: [300, 300]), 
                        class: "object-fill mx-0" %>
                <% else %>
                    <%= image_tag(image_path('upload_image.png'), class: "object-fill p-8") %>
                <% end %>
            </figure>
        </div>
        <div class="flex-1 mx-10 flex flex-col justify-between align-center">
            <div class="text-2xl text-center pb-6 pt-6 md:pt-0">Aftermath:</div>
            <div class="text-lg flex-1">
                    <%= simple_format @summary.aftermath %>
            </div>
        </div>
    </div>
</div>
<div class="bg-white flex flex-col md:flex-row">
    <div class="mx-10 p-6 flex flex-col items-center flex-1">
        <div class="text-2xl text-center pt-4">
            Key Points:
        </div>
        <ul class="py-6 list-disc text-lg">
            <% @summary.key_points.each do |key_point| %>
                <li class="mb-4"><%= key_point %></li>
            <% end %>
        </ul>
    </div>
    <div class="px-16 py-6 flex flex-col items-center flex-1 bg-[beige]">
            <div class="text-2xl text-center py-4">
                Process Diagram:
            </div>
            <% if @process_diagram.representable? %>
                <%= image_tag @process_diagram.representation(resize_to_limit: [300, 300]), 
                    class: "flex-1 border border-black border-4 object-fill my-4" %>
            <% else %>
                <%= image_tag(image_path('upload_image.png'), class: "object-contain") %>
            <% end %>
    </div>
</div>
<% if @summary.alternatives_count > 0 %>
    <div class="bg-[#F7FCFC] pt-4">
        <div class="text-2xl text-center py-6">
            <span>Alternatives:</span>
        </div>
        <div class="mx-10 px-6 pb-6 flex flex-col items-center justify-center">
            <% @summary_alternatives.each do |alternative| %>
                <div class="flex mx-6 mb-4 items-center border border-slate-300 rounded bg-white w-full">
                    <div class="flex-1 flex flex-col p-4 items-center self-start"> 
                        <span class="text-lg font-semibold pb-4"><%= alternative.title %></span>
                        <span><%= alternative.description %></span>
                    </div>     
                    <div class="flex pl-4 self-start flex-1">
                        <div class="flex-col flex flex-1 mr-4">
                            <span class="py-4">Pros:</span>
                            <span><%= alternative.pros %></span>
                        </div>
                        <div class="flex-col flex flex-1 mr-4">
                            <span class="py-4">Cons:</span>
                            <span><%= alternative.pros %></span>
                        </div>
                    </div>
                </div>                     
            <% end %>
        </div>
    </div>   
<% end %>   
<div class="bg-[#F7FCFC]">
    <div class="mx-10 p-6 flex flex-col items-center">
        <div class="text-2xl text-center pt-4">
            Further Reading:
        </div>
        <ul class="py-6 list-disc text-lg">
            <% @summary.sources.each do |source| %>
                <li class="mb-4"><%= link_to source, source, class: "hover:underline hover:text-blue-400" %></li>
            <% end %>
        </ul>
    </div>
</div>