config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'theory_points/new'
  end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :admin do 
    get 'login', to: "sessions#new", as: "login"
    post 'login', to: "sessions#create"
    delete 'logout', to: "sessions#destroy", as: "logout"

    resources :subjects, shallow: true, only: [:index, :create], param: "slug" do
        resources :lessons, only: [:create, :index, :edit, :destroy, :update, :show], param: "lesson_slug" do
        end
        resources :lessons, param: "slug" do 
            get "index_show" # to 'lessons#index_show' action.
        end
    end

    resources :subjects, only: [:update, :destroy, :edit], param: "subject_slug"

    resources :lessons, param: "slug", only: [] do 
      resources :lesson_pages, only: [:show, :edit, :update, :destroy, :create], param: "lesson_page_id", shallow: true
      resource :problem, only: [:show, :edit, :update], param: "problem_id"
      resource :summary, only: [:show, :edit, :update], param: "problem_id"
    end

    resources :lesson_pages, only: [], shallow: true do
      resources :theory_points, only: [:new, :create, :destroy], shallow: true
    end

    resources :summaries, only: [] do
      resources :alternatives, only: [:new, :create, :edit, :update, :show, :destroy]
    end
  end
  # Defines the root path route ("/")
  root to: "subjects#index" 
  get '/about', to: "pages#about", as: "about"
  get '/recruiters', to: "pages#recruiters", as: "recruiters"

  get '/:subject_slug/lessons', to: "lessons#index_by_subject", as: 'lessons' 
  get '/lesson/:lesson_slug', to: "lessons#show", as: 'lesson'
  get '/lesson/:lesson_slug/problem', to: "problem#show", as: 'problem'
  get '/lesson/:lesson_slug/part-(:lesson_page_id)', to: "lesson_pages#show", as: 'lesson_page'
  get '/lesson/:lesson_slug/summary', to: "summary#show", as: 'summary'
end

app/models/alternative.rb
class Alternative < ApplicationRecord
  belongs_to :summary, counter_cache: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_secure_password

  has_many :subjects
end

app/models/device_user.rb
class DeviceUser < ApplicationRecord
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  after_create :createInitialPages
  after_create :addIdToSubject

  after_destroy :removeIdFromSubject

  belongs_to :subject

  has_one :problem, dependent: :destroy
  has_one :summary, dependent: :destroy

  has_one_attached :image

  has_many :lesson_pages, dependent: :destroy

  def to_param
    return nil unless persisted?
    self.title.downcase.gsub(' ', '-') # 1-english-for-everyone
  end

  def createInitialPages
      self.create_problem!(title: "Untitled Problem")
      self.create_summary!(aftermath: "Empty Aftermath Description")
      page = self.lesson_pages.create!(title: "Untitled Page")
      self.update!(page_id_order: [page.id])
  end

  def addIdToSubject
      self.subject.addLessonId(self.id)
  end

  def removeIdFromSubject
      self.subject.removeLessonId(self.id)
  end
end

app/models/lesson_objective.rb
class LessonObjective < ApplicationRecord
  belongs_to :lesson
end

app/models/lesson_page.rb
class LessonPage < ApplicationRecord
  belongs_to :lesson, counter_cache: true

  has_many :theory_points
  accepts_nested_attributes_for :theory_points

end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :lesson

  has_one_attached :image
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :summary
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :creator
    has_many :lessons

    has_one_attached :image

    def to_param
        return nil unless persisted?
        self.title.downcase.gsub(' ', '-') # 1-english-for-everyone
    end

    def addLessonId(num)
        new_order = self.lesson_id_order.unshift(num)
        self.update!(lesson_id_order: new_order)
    end

    def removeLessonId(num)
        new_order = self.lesson_id_order - [num]
        self.update(lesson_id_order: new_order)
    end
end

app/models/summary.rb
class Summary < ApplicationRecord
  has_many :alternatives

  has_one_attached :aftermath_image
  has_one_attached :process_diagram

  belongs_to :lesson
end

app/models/theory_point.rb
class TheoryPoint < ApplicationRecord
  belongs_to :lesson_page

  has_one_attached :image
end

app/controllers/admin/problems_controller.rb
class Admin::ProblemsController < ApplicationController
  layout "admin"

  def show
      @lesson = Lesson.find_by(title: lesson_title_param)
      @subject = @lesson.subject

      @lesson_pages = LessonPage.find(@lesson.page_id_order)
      @problem = @lesson.problem
      @problem_image = @problem.image

      @first_lesson_page = LessonPage.find(@lesson.page_id_order[0])
  end

  def edit
      @lesson = Lesson.find_by(title: lesson_title_param)
      @problem = @lesson.problem
      @problem_image = @problem.image
  end

  def update
      @lesson = Lesson.find_by(title: lesson_title_param)
      @subject = @lesson.subject

      @lesson_pages = @lesson.lesson_pages
      @problem = @lesson.problem
      @problem.update!(problem_params)

      @problem_image = @problem.image

      @first_lesson_page = LessonPage.find(@lesson.page_id_order[0])

      flash[:notice] = 'Problem updated successfully'
      redirect_to admin_lesson_problem_path(@lesson)
  end 

  private 

  def problem_params
    params.require(:problem).permit(:title, :image_subtitle, :description, :simon_says, :did_you_know, :image)
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :description, :image, :objectives)
  end

  def lesson_id_params
    params.permit(:id)
  end

  def subject_title_param
    params[:subject_slug]&.gsub("-", " ")&.capitalize
  end

  def lesson_title_param
    params[:lesson_slug]&.gsub("-", " ")&.capitalize
  end  
end

app/controllers/problem_controller.rb
class ProblemController < ApplicationController
  def show
    @lesson = Lesson.find_by(title: lesson_title_param)
    @problem = @lesson.problem
    @summary = @lesson.summary

    @lesson_pages = LessonPage.find(@lesson.page_id_order)
    @subject = @lesson.subject
    @current_page = "problem"

    @image = @problem.image
  end

  private 

  def lesson_title_param
    title = deslug(params[:lesson_slug])
  end

  def deslug(str)
    if str.present?
      str.gsub("-", " ").capitalize
    end
  end

end

app/helpers/admin/problems_helper.rb
module Admin::ProblemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_users_helper.rb
module DeviceUsersHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/admin/problems/_page_list.html.erb
<div class="flex flex-col flex-nowrap items-end overflow-y-scroll flex-1" id="lesson_pages_list">
    <div class="mb-3 w-[15rem] selected lesson_page_button flex-0 group rounded px-6 py-2 shadow-md flex text-xl font-semibold ">
        Problem
    </div>
    <% lesson_pages.each do |lesson_page| %>
            <%= link_to admin_lesson_page_path(lesson_page), class: "mb-3 w-[15rem] unselected lesson_page_button flex-0 group rounded px-6 py-2 shadow-md flex items-center flex-col h-fit", data: { turbo_frame: "show_lesson" } do %>
                        <div class="w-full flex justify-between items-center">
                            <span class="text-xl font-semibold group-hover:underline flex-1">
                                <%= lesson_page.title.capitalize %>
                            </span>
                        </div>
            <% end %>
    <% end %>
    <%= link_to "Summary", admin_lesson_summary_path(lesson), class:"mb-3 w-[15rem] unselected lesson_page_button flex-0 
                           group rounded px-6 py-2 shadow-md flex text-xl font-semibold " %>
</div>

app/views/admin/problems/edit.html.erb
<!-- <%= turbo_frame_tag "edit_problem_page" do %>
    <%= form_with(model: @problem, scope: :problem, method: :patch, url: admin_lesson_problem_path(@lesson), data: { 'admin-target': "editLessonProblemForm" } ) do |f| %>
            <div class="title text-center text-4xl bg-slate-200 py-4">
                <%= f.text_field :title, class: "text-center text-4xl flex-1 pl-4 my-3 bg-slate-200
                border-0 border-b border-solid border-b-blue-300 focus:border-b-blue-800 focus:ring-0" %>
            </div>
            <div class="flex md:flex-row flex-col">
                    <label for="problem_image_uploads" class="flex-1 flex flex-col justify-center hover:cursor-pointer">
                        <% if @problem_image.representable? %>
                                <%= image_tag(@problem_image.representation(resize_to_limit: [300, 300]), data: { 'admin-target':'imageBox' },
                                class: "object-fill") %>
                        <% else %>
                            <%= image_tag(image_path('upload_image.png'), class: "object-fill",  data: { 'admin-target':'imageBox' }) %>
                        <% end %>
                        <%= f.file_field :image, type: "file", id: "problem_image_uploads", accept: ".png, .jpeq, .jpg, .webP", 
                                class: "image_file hidden", data: { 'action': 'change->admin#display_image', 'admin-target':'imageInput' } %>
                    </label>
                    <div class="flex-1 min-w-0 flex flex-col justify-between align-center">
                        <%= f.text_field :image_subtitle, class: "text-2xl font-light italic text-center flex-1 pl-4 
                                    border-0 border-b border-solid  border-b-blue-300 focus:border-b-blue-800 focus:ring-0 mb-6 mx-4 mt-4" %>
                        <div class="text-xl text-center">Description:</div>
                        <%= f.text_area :description, class: "p-2 text-lg flex-1 text-center m-4", rows: "10" %>
                    </div>
            </div>
            <div class="bg-[#F7FCFC] flex flex-col md:flex-row">
                <div class="px-4 py-6 flex flex-col items-center flex-1 bg-[beige]">
                    <div class="text-2xl text-center w-full">
                        <%= f.label :simon_says, class: "" %>
                        <%= f.text_area :simon_says, class: "sb1 my-4 w-full" %>
                    </div>
                </div>
                <div class="px-4 py-6 flex flex-col items-center flex-1">
                    <div class="text-2xl text-center pb-4">
                        Did you know?
                    </div>
                    <%= f.text_area :did_you_know, class: "w-full mx-4" %>
                </div>
            </div>
    <% end %>
<% end %>
        -->

app/views/admin/problems/show.html.erb
<div class="flex flex-row px-6 pb-8">
      <div class="flex flex-col flex-nowrap mx-4 mt-6">
            <div class="flex pb-4 mr-4 justify-center">
                <span class="text-2xl font-bold align-center"><%= @lesson.title %></span>
            </div>
            <div class="flex justify-between pb-6 mr-4">
                <span class="text-xl self-center"><%= pluralize(@lesson.lesson_pages_count, 'Page') %></span>
                <%= button_to "+ New", admin_lesson_lesson_pages_path(@lesson), method: :post, class: "px-4 py-1 btn btn-blue text-md font-light rounded self-end" %>
            </div>
            <%= render partial: 'admin/problems/page_list', locals: { lesson_pages: @lesson_pages, lesson: @lesson } %>
            <div class="flex flex-col flex-nowrap">
                <div class="flex my-4 mr-4">
                    <%= link_to "Next", admin_lesson_page_path(@first_lesson_page),  
                        class:"btn btn-blue justify-center flex flex-1 rounded px-6 py-2 shadow-md text-sm font-light hover:cursor-pointer" %>
                </div>
            </div>
      </div>
      <div class="flex flex-col flex-1">
        <div class="flex justify-between py-4">
            <span class="text-lg self-center">
                <%= link_to "Lessons", admin_lesson_index_show_path(@lesson), class: "hover:underline hover:text-blue-700" %>
                <%= " > #{@lesson.title} > #{@problem.title}" %>
            </span>
            <span>
                <div class="flex" data-admin-target="pageEditButtons">    
                <button class="btn btn-blue border-black bg-slate-grey text-md font-light rounded mr-2" data-action="admin#updateProblemPage">
                    Update Page
                </button>
                    <%= link_to "Preview", problem_path(@lesson), class: "btn btn-blue text-md font-light rounded" %>
                </div>
                <div class="hidden" data-admin-target="pageUpdateButtons">
                <%= link_to "Cancel", admin_lesson_problem_path(@lesson), data: { action: "clicked->admin#show_page_edit_buttons" },
                    class: "bg-gray-200 hover:bg-gray-300 text-sm text-gray-700 px-4 py-2 border-black bg-slate-grey rounded" %>
                </div>
            </span>
        </div>
        <div class="flex flex-1 overflow-y-scroll max-h-[35rem] border border-black flex-col">
                <%= form_with(model: @problem, scope: :problem, method: :patch, url: admin_lesson_problem_path(@lesson), data: { 'admin-target': "editLessonProblemForm" } ) do |f| %>
                        <div class="title text-center text-4xl bg-slate-200 py-4">
                            <%= f.text_field :title, class: "text-center text-4xl flex-1 pl-4 my-3 bg-slate-200
                            border-0 border-b border-solid border-b-blue-300 focus:border-b-blue-800 focus:ring-0" %>
                        </div>
                        <div class="flex md:flex-row flex-col">
                                <label for="problem_image_uploads" class="px-4 flex-1 flex flex-col justify-center hover:cursor-pointer">
                                    <% if @problem_image.representable? %>
                                            <%= image_tag(@problem_image.representation(resize_to_limit: [300, 300]), data: { 'admin-target':'imageBox' },
                                            class: "object-fill") %>
                                    <% else %>
                                        <%= image_tag(image_path('upload_image.png'), class: "object-fill",  data: { 'admin-target':'imageBox' }) %>
                                    <% end %>
                                    <%= f.file_field :image, type: "file", id: "problem_image_uploads", accept: ".png, .jpeq, .jpg, .webP", direct_upload: true,
                                            class: "image_file hidden", data: { 'action': 'change->admin#display_image', 'admin-target':'imageInput' } %>
                                </label>
                                <div class="flex-1 min-w-0 flex flex-col justify-between align-center">
                                    <%= f.text_field :image_subtitle, class: "text-2xl font-light italic text-center flex-1 pl-4 
                                                border-0 border-b border-solid  border-b-blue-300 focus:border-b-blue-800 focus:ring-0 mb-6 mx-4 mt-4" %>
                                    <div class="text-xl text-center">Description:</div>
                                    <%= f.text_area :description, class: "p-2 text-lg flex-1 text-center m-4", rows: "10" %>
                                </div>
                        </div>
                        <div class="bg-[#F7FCFC] flex flex-col md:flex-row">
                            <div class="px-4 py-6 flex flex-col items-center flex-1 bg-[beige]">
                                <div class="text-2xl text-center w-full">
                                    <%= f.label :simon_says, class: "" %>
                                    <%= f.text_area :simon_says, class: "sb1 my-4 w-full" %>
                                </div>
                            </div>
                            <div class="px-4 py-6 flex flex-col items-center flex-1">
                                <div class="text-2xl text-center pb-4">
                                    Did you know?
                                </div>
                                <%= f.text_area :did_you_know, class: "w-full mx-4" %>
                            </div>
                        </div>
                <% end %>
        </div>
      </div>
</div>

<!-- <%= link_to "Prev", class:"btn btn-blue justify-center flex flex-1 rounded px-6 py-2 shadow-md text-lg font-light hover:cursor-pointer" %> -->

app/views/problem/show.html.erb
<nav class="sticky top-0 flex justify-between bg-zinc-100 items-center" data-controller="lesson-nav">
    <div class="md:static relative w-full flex justify-between">
        <%= link_to "Next >", '#',
            class:"invisible px-4 py-2 md:py-4 flex-0 border-black bg-slate-grey md:text-2xl text-xl font-light rounded" %>
        <div data-action="click->lesson-nav#toggle_page_list" class="static md:relative flex-1 flex justify-center md:max-w-[30rem]">
            <div class="justify-center items-center h-full hover:cursor-pointer hover:bg-sky-100 flex flex-1">
                <%= image_tag(image_path('page_list.png'), class: "object-fill pr-2") %>
                <span class="text-xl hidden sm:inline"><%= @lesson.title %></span>
            </div>
            <%= render partial: "shared/page_list", locals: { lesson: @lesson, subject: @subject, lesson_pages: @lesson_pages, 
                problem: @problem, summary: @summary, current_page: @current_page } %>
        </div>
        <%= link_to "Next >", lesson_page_path(@lesson, 1),
            class:"hover:bg-sky-100 px-4 py-2 md:py-4 flex-0 border-black bg-slate-grey md:text-2xl text-xl font-light rounded" %>
    </div>
</nav>
<div class="title py-6 text-center text-2xl md:text-4xl bg-slate-200">
  <div class="md:py-6"><%= @problem.title %></div>
</div>
<div class="flex lg:flex-row flex-col m-10 px-0 md:px-6">
      <figure class="flex-shrink-0 md:mr-6 flex flex-col justify-center">
        <% if @image.representable? %>
            <%= image_tag @image.representation(resize_to_limit: [400, 400]), class: "flex-1 object-contain" %>
        <% end %>
      </figure>
      <div class="flex-1 md:ml-6 flex flex-col justify-between align-center">
          <div class="text-3xl font-light pt-6 md:pt-0 pb-6"><%= @problem.image_subtitle %></div>
          <div class="text-lg flex-1">
                <%= simple_format @problem.description %>
          </div>
      </div>
</div>
<div class="bg-[#F7FCFC] flex flex-col md:flex-row">
    <div class="px-10 md:px-16 py-6 flex flex-col items-center flex-1 bg-[beige]">
        <div class="text-2xl pt-4">
            <div class="sb1 px-6 py-8"><%= simple_format @problem.simon_says %></div>
        </div>
    </div>
    <div class="mx-10 px-0 md:px-6 py-6 flex flex-col items-center flex-1">
        <div class="text-2xl text-center pt-4">
            Did you know?
        </div>
        <div class="text-lg pt-6">
            <%= simple_format @problem.did_you_know %>
        </div>
    </div>
</div>