config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'theory_points/new'
  end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :admin do 
    get 'login', to: "sessions#new", as: "login"
    post 'login', to: "sessions#create"
    delete 'logout', to: "sessions#destroy", as: "logout"

    resources :subjects, shallow: true, only: [:index, :create], param: "slug" do
        resources :lessons, only: [:create, :index, :edit, :destroy, :update, :show], param: "lesson_slug" do
        end
        resources :lessons, param: "slug" do 
            get "index_show" # to 'lessons#index_show' action.
        end
    end

    resources :subjects, only: [:update, :destroy, :edit], param: "subject_slug"

    resources :lessons, param: "slug", only: [] do 
      resources :lesson_pages, only: [:show, :edit, :update, :destroy, :create], param: "lesson_page_id", shallow: true
      resource :problem, only: [:show, :edit, :update], param: "problem_id"
      resource :summary, only: [:show, :edit, :update], param: "problem_id"
    end

    resources :lesson_pages, only: [], shallow: true do
      resources :theory_points, only: [:new, :create, :destroy], shallow: true
    end

    resources :summaries, only: [] do
      resources :alternatives, only: [:new, :create, :edit, :update, :show, :destroy]
    end
  end
  # Defines the root path route ("/")
  root to: "subjects#index" 
  get '/about', to: "pages#about", as: "about"
  get '/recruiters', to: "pages#recruiters", as: "recruiters"

  get '/:subject_slug/lessons', to: "lessons#index_by_subject", as: 'lessons' 
  get '/lesson/:lesson_slug', to: "lessons#show", as: 'lesson'
  get '/lesson/:lesson_slug/problem', to: "problem#show", as: 'problem'
  get '/lesson/:lesson_slug/part-(:lesson_page_id)', to: "lesson_pages#show", as: 'lesson_page'
  get '/lesson/:lesson_slug/summary', to: "summary#show", as: 'summary'
end

app/models/alternative.rb
class Alternative < ApplicationRecord
  belongs_to :summary, counter_cache: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_secure_password

  has_many :subjects
end

app/models/device_user.rb
class DeviceUser < ApplicationRecord
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  after_create :createInitialPages
  after_create :addIdToSubject

  after_destroy :removeIdFromSubject

  belongs_to :subject

  has_one :problem, dependent: :destroy
  has_one :summary, dependent: :destroy

  has_one_attached :image

  has_many :lesson_pages, dependent: :destroy

  def to_param
    return nil unless persisted?
    self.title.downcase.gsub(' ', '-') # 1-english-for-everyone
  end

  def createInitialPages
      self.create_problem!(title: "Untitled Problem")
      self.create_summary!(aftermath: "Empty Aftermath Description")
      page = self.lesson_pages.create!(title: "Untitled Page")
      self.update!(page_id_order: [page.id])
  end

  def addIdToSubject
      self.subject.addLessonId(self.id)
  end

  def removeIdFromSubject
      self.subject.removeLessonId(self.id)
  end
end

app/models/lesson_objective.rb
class LessonObjective < ApplicationRecord
  belongs_to :lesson
end

app/models/lesson_page.rb
class LessonPage < ApplicationRecord
  belongs_to :lesson, counter_cache: true

  has_many :theory_points
  accepts_nested_attributes_for :theory_points

end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :lesson

  has_one_attached :image
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :summary
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :creator
    has_many :lessons

    has_one_attached :image

    def to_param
        return nil unless persisted?
        self.title.downcase.gsub(' ', '-') # 1-english-for-everyone
    end

    def addLessonId(num)
        new_order = self.lesson_id_order.unshift(num)
        self.update!(lesson_id_order: new_order)
    end

    def removeLessonId(num)
        new_order = self.lesson_id_order - [num]
        self.update(lesson_id_order: new_order)
    end
end

app/models/summary.rb
class Summary < ApplicationRecord
  has_many :alternatives

  has_one_attached :aftermath_image
  has_one_attached :process_diagram

  belongs_to :lesson
end

app/models/theory_point.rb
class TheoryPoint < ApplicationRecord
  belongs_to :lesson_page

  has_one_attached :image
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/shared/_flash.html.erb
<div data-controller="flash" id="flash" class="flex items-center fixed bottom-4 left-6 py-3 px-5 bg-[#DCF2D4]">
    <div class="mr-4 value-holder"><%= (flash[:notice] || @message) %></div>

    <button type="button" data-action="flash#dismiss">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
    </button>
</div>

app/views/shared/_page_list.html.erb
<div data-lesson-nav-target="pageList" class="overflow-y-scroll flex-col p-4 absolute h-[50vh] bottom-[-50vh] border-8 w-full border-slate-300 bg-white hidden">
    <div class="text-lg font-light ">
        <%= link_to "Subjects", admin_subjects_path, class: "hover:underline hover:text-blue-700" %>
        <span> > </span>
        <%= link_to "#{subject.title}", admin_subject_lessons_path(subject), class: "hover:underline hover:text-blue-700" %>
    </div>        
    <div class="flex flex-wrap items-center">
        <span class="text-2xl pr-2"><%= lesson.title %></span>
        <span class="text-xl font-light">(<%= pluralize(lesson.page_id_order.count + 2, 'page') %>)</span>
    </div>
    <ul class="list-disc text-lg ml-6 pl-6 pt-4 flex flex-1 flex-col">
        <% if (current_page == "problem") %>
            <li class="border-l-[#3949ab] border-slate-300 border-l-4 border-y border-r bg-indigo-50 p-2">Problem
            </li>
        <% else %>
            <li class="hover:underline hover:text-blue-700 hover:bg-indigo-50">
                <%= link_to "#{problem.title}", problem_path(lesson), class: "w-full p-2 flex" %>
            </li>
        <% end %>
        <ol class="list-decimal">
            <% lesson_pages.each.with_index(1) do |lesson_page, index| %>
                <% if (current_page == "page_#{lesson_page.id}") %>
                    <li class="border-l-[#3949ab] border-slate-300 border-l-4 border-y border-r bg-indigo-50 p-2">
                        <%= lesson_page.title %>
                    </li>
                <% else %>
                    <li class="hover:underline hover:text-blue-700 hover:bg-indigo-50">
                        <%= link_to "#{lesson_page.title}", lesson_page_path(lesson, index), class: "w-full p-2 flex" %>
                    </li>
                <% end %>
            <% end %>
        </ol>
        <% if (current_page == "summary") %>
            <li class="border-l-[#3949ab] border-slate-300 border-l-4 border-y border-r bg-indigo-50 p-2">Summary
            </li>
        <% else %>
            <li class="hover:underline hover:text-blue-700 hover:bg-indigo-50">
                <%= link_to "Summary", summary_path(lesson), class: "w-full p-2 flex" %>
            </li>
        <% end %>
    </ul>
</div>