config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'theory_points/new'
  end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :admin do 
    get 'login', to: "sessions#new", as: "login"
    post 'login', to: "sessions#create"
    delete 'logout', to: "sessions#destroy", as: "logout"

    resources :subjects, shallow: true, only: [:index, :create], param: "slug" do
        resources :lessons, only: [:create, :index, :edit, :destroy, :update, :show], param: "lesson_slug" do
        end
        resources :lessons, param: "slug" do 
            get "index_show" # to 'lessons#index_show' action.
        end
    end

    resources :subjects, only: [:update, :destroy, :edit], param: "subject_slug"

    resources :lessons, param: "slug", only: [] do 
      resources :lesson_pages, only: [:show, :edit, :update, :destroy, :create], param: "lesson_page_id", shallow: true
      resource :problem, only: [:show, :edit, :update], param: "problem_id"
      resource :summary, only: [:show, :edit, :update], param: "problem_id"
    end

    resources :lesson_pages, only: [], shallow: true do
      resources :theory_points, only: [:new, :create, :destroy], shallow: true
    end

    resources :summaries, only: [] do
      resources :alternatives, only: [:new, :create, :edit, :update, :show, :destroy]
    end
  end
  # Defines the root path route ("/")
  root to: "subjects#index" 
  get '/about', to: "pages#about", as: "about"
  get '/recruiters', to: "pages#recruiters", as: "recruiters"

  get '/:subject_slug/lessons', to: "lessons#index_by_subject", as: 'lessons' 
  get '/lesson/:lesson_slug', to: "lessons#show", as: 'lesson'
  get '/lesson/:lesson_slug/problem', to: "problem#show", as: 'problem'
  get '/lesson/:lesson_slug/part-(:lesson_page_id)', to: "lesson_pages#show", as: 'lesson_page'
  get '/lesson/:lesson_slug/summary', to: "summary#show", as: 'summary'
end

app/models/lesson_page.rb
class LessonPage < ApplicationRecord
  belongs_to :lesson, counter_cache: true

  has_many :theory_points
  accepts_nested_attributes_for :theory_points

end

app/controllers/admin/lesson_pages_controller.rb
class Admin::LessonPagesController < ApplicationController
  layout "admin"

  def show
    @page = LessonPage.find(params[:lesson_page_id])
    @page_theory_points = @page.theory_points
    @page_exercises = @page.exercises

    @lesson = @page.lesson
    @subject = @lesson.subject

    @lesson_pages = LessonPage.find(@lesson.page_id_order)

    page_order = @lesson.page_id_order
    page_index = page_order.index(@page.id)

    @prev_lesson_page = (page_index == 0) ? nil : LessonPage.find(page_order[page_index - 1])
    @next_lesson_page = (page_order[page_index + 1]).present? ? LessonPage.find(page_order[page_index + 1]) : nil
  end

  def new
  end

  def index
  end

  def create
    lesson = Lesson.find_by(title: lesson_title_param)
    @page = LessonPage.create!(lesson_id: lesson.id, title: "Untitled")
    lesson.update!(page_id_order: lesson.page_id_order.unshift(@page.id))
    
    redirect_to admin_lesson_page_path(@page)
  end

  def edit
    @page = LessonPage.find(page_params[:lesson_page_id])
    @page_theory_points = @page.theory_points
    @page_exercises = @page.exercises

    @lesson = @page.lesson
    @subject = @lesson.subject

    @lesson_pages = @lesson.lesson_pages

    #page_order = @lesson.page_id_order
    #page_index = page_order.index(@page.id)

    #@prev_lesson_page = (page_index == 0) ? nil : LessonPage.find(page_order[page_index - 1])
    #@next_lesson_page = (page_order[page_index + 1]).present? ? LessonPage.find(page_order[page_index + 1]) : nil
  end

  def update
    @page = LessonPage.find(page_params[:lesson_page_id])
    @lesson = @page.lesson
    @subject = @lesson.subject

    @lesson_pages = @lesson.lesson_pages.order(:index)

    @page.update!(page_update_params)

    # if the new index does not point to the same page id
    # which will be in the case when the index id has been recently updated.
    index_arr = @lesson.page_id_order
    new_index = page_index_params[:index].to_i
    if (index_arr[new_index] != @page.id)
      index_arr.delete(@page.id)
      index_arr.insert(new_index, @page.id)
      @lesson.update(page_id_order: index_arr)
    end

    flash[:notice] = 'Lesson Page updated successfully'
    redirect_to admin_lesson_page_path(@page)
  end

  def destroy
    @page = LessonPage.find(page_params[:lesson_page_id])
    @lesson = @page.lesson

    page_order = @lesson.page_id_order
    page_order.delete(@page.id)

    @lesson.update!(page_id_order: page_order)
    @page.destroy!

    flash[:notice] = 'Lesson deleted successfully'
    redirect_to admin_lesson_problem_path(@lesson)
  end

  private 

  def page_params
    params.permit(:lesson_page_id)
  end

  def page_update_params
    update_params =  params.require(:lesson_page).permit(:title, :exercises, :answers, :theory_points_attributes => [:id, :title, :description, :lesson_page_id, :image])
    update_params[:exercises] = update_params[:exercises].present? ? JSON.parse(update_params[:exercises]) : ''
    update_params[:answers] = update_params[:answers].present? ? JSON.parse(update_params[:answers]) : ''
    return update_params
  end

  def page_index_params
    params.require(:lesson_page).permit(:index)
  end

  def lesson_title_param
    title = deslug(params[:lesson_slug])
  end  

  def deslug(str)
    if str.present?
      str.gsub("-", " ").capitalize!
    end
  end
end

app/controllers/lesson_pages_controller.rb
class LessonPagesController < ApplicationController
  def show
      @page_index = page_index_param[:lesson_page_id].to_i      

      @lesson = Lesson.find_by(title: lesson_title_param)
      @page = LessonPage.find(@lesson.page_id_order[(@page_index - 1)])
      @theory_points = @page.theory_points.order(:order_index)
      @exercises = @page.exercises

      @subject = @lesson.subject
      @lesson_pages = LessonPage.find(@lesson.page_id_order)
      @problem = @lesson.problem
      @summary = @lesson.summary

      @current_page = "page_#{@page.id}"
  end

  private

  def subject_title_param
    title = deslug(params[:subject_slug])
  end

  def lesson_title_param
    title = deslug(params[:lesson_slug])
    title.capitalize
  end

  def page_index_param
    params.permit(:lesson_page_id)
  end

  def deslug(str)
    if str.present?
      str.gsub("-", " ").downcase
    end
  end

end

app/helpers/admin/lesson_pages_helper.rb
module Admin::LessonPagesHelper
end

app/views/admin/lesson_pages/_page_list.html.erb
<div class="flex flex-col flex-nowrap items-end overflow-y-scroll flex-1" id="lesson_pages_list">
    <%= link_to "Problem", admin_lesson_problem_path(lesson), class: "mb-3 w-[15rem] unselected lesson_page_button flex-0 
                            group rounded px-6 py-2 shadow-md flex text-xl font-semibold " %>
    <% lesson_pages.each do |lesson_page| %>
            <%= link_to admin_lesson_page_path(lesson_page), class: ("mb-3 w-[15rem] lesson_page_button 
                        flex-0 group rounded px-6 py-2 shadow-md flex items-center flex-col h-fit" + (current_page.id == lesson_page.id ? " selected" : " unselected")), 
                        data: { turbo_frame: "show_lesson", 'index': lesson.page_id_order.index(lesson_page.id) } do %>
                        <div class="w-full flex justify-between items-center">
                            <span class="text-xl font-semibold group-hover:underline flex-1">
                                <%= lesson_page.title.capitalize %>
                            </span>
                        </div>
            <% end %>
    <% end %>
    <%= link_to "Summary", admin_lesson_summary_path(lesson), class: "mb-3 w-[15rem] unselected lesson_page_button flex-0 
                            group rounded px-6 py-2 shadow-md flex text-xl font-semibold " %>
    <!-- button_to "New lesson page", admin_lesson_lesson_pages_path(lesson), method: :post, class: "btn btn-blue text-sm font-light rounded self-end",
                            data: { turbo_frame: "new_lesson_page" } -->
</div>

app/views/admin/lesson_pages/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::LessonPages#create</h1>
  <p>Find me in app/views/admin/lesson_pages/create.html.erb</p>
</div>

app/views/admin/lesson_pages/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::LessonPages#destroy</h1>
  <p>Find me in app/views/admin/lesson_pages/destroy.html.erb</p>
</div>

app/views/admin/lesson_pages/edit.html.erb
<%= turbo_frame_tag "edit_lesson_page" do %>
    <%= form_with(model: @page, scope: :lesson_page, method: :patch, url: admin_lesson_page_path(@page), 
        data: { 'admin-target': "editLessonPageForm" } ) do |f| %>
        <div class="title flex justify-between text-4xl bg-slate-200 py-4">
            <%= f.text_field :title, class: "text-4xl text-center shrink min-w-0 pl-4 my-3 ml-4 bg-slate-200
            border-0 border-b border-solid border-b-blue-300 focus:border-b-blue-800 focus:ring-0" %>
            <div class="flex flex-col mx-6">
                <%= f.hidden_field :index, value: @lesson.page_id_order.index(@page.id), data: { 'max-index': @lesson.lesson_pages_count } %>
                <span data-action="click->admin#move_page_up" class="w-[6rem] btn-blue
                        font-light px-2 py-2 border-black text-sm text-center rounded hover:cursor-pointer align-end">
                    Move up
                </span>
                <span data-action="click->admin#move_page_down" class="w-[6rem] btn-blue
                        font-light px-2 py-2 border-black text-sm text-center rounded mt-2 hover:cursor-pointer align-end">
                    Move down
                </span>
            </div>
        </div>
        <% @page_theory_points.each_with_index do |theory_point, index| %> 
            <%= f.fields_for :theory_points, theory_point do |ff| %>
                <% if (index.even?) %>
                    <div class="bg-white">
                        <%= link_to admin_theory_point_path(theory_point), data: { 'turbo-method': :delete,  'turbo-confirm': "Are you sure?" } do %>
                            <span class="cross">&#9587;</span>
                        <% end %>
                        <div class="pt-6 flex flex-col md:flex-row mb-4">
                            <div class="px-6 flex flex-col items-center justify-center">
                                <label for=<%= "theory_point_image_uploads_#{index}" %> class="hover:cursor-pointer max-w-[8rem]">
                                    <% if theory_point.image.representable? %>
                                            <%= image_tag(theory_point.image.representation(resize_to_limit: [300, 300]), data: { 'admin-target':'imageBox' },
                                            class: "object-fill") %>
                                    <% else %>
                                        <%= image_tag(image_path('upload_image.png'), class: "object-fill",  data: { 'admin-target':'imageBox' }) %>
                                    <% end %>
                                    <%= ff.file_field :image, type: "file", id: "theory_point_image_uploads_#{index}", accept: ".png, .jpeq, .jpg, .webP", direct_upload: true,
                                            class: "image_fill hidden", data: { 'action': 'change->admin#display_image', 'admin-target':'imageInput' } %>
                                </label>
                            </div>
                            <div class="flex flex-col items-center flex-1">
                                <%= ff.text_field :title, class: "w-[85%] px-2 py-0 text-lg font-light italic text-center
                                    border-0 border-b border-solid border-b-blue-300 focus:border-b-blue-800 focus:ring-0" %>
                                <%= ff.text_area :description, class: "p-2 text-md text-center m-4 w-[85%]", rows: "6" %>
                                <%= ff.hidden_field :lesson_page_id, value: @page.id  %>
                            </div>
                        </div>
                    </div>  
                <% else %>
                    <div class=" bg-[#F7FCFC]">
                        <%= link_to admin_theory_point_path(theory_point), data: { 'turbo-method': :delete, 'turbo-confirm': "Are you sure?" } do %>
                            <span class="cross">&#9587;</span>
                        <% end %>
                        <div class="pt-6 flex flex-col md:flex-row mb-4">
                            <div class="flex flex-col items-center flex-1">
                                <%= ff.text_field :title, class: "w-[85%] px-2 py-0 text-lg font-light italic text-center
                                    border-0 border-b border-solid border-b-blue-300 focus:border-b-blue-800 focus:ring-0" %>
                                <%= ff.text_area :description, class: "p-2 text-md text-center m-4 w-[85%]", rows: "6" %>
                                <%= ff.hidden_field :lesson_page_id, value: @page.id  %>
                            </div>
                            <div class="px-6 flex flex-col items-center justify-center">
                                <label for=<%= "theory_point_image_uploads_#{index}" %> class="hover:cursor-pointer max-w-[8rem]">
                                    <% if theory_point.image.representable? %>
                                            <%= image_tag(theory_point.image.representation(resize_to_limit: [300, 300]), data: { 'admin-target':'imageBox' },
                                            class: "object-fill") %>
                                    <% else %>
                                        <%= image_tag(image_path('upload_image.png'), class: "object-fill",  data: { 'admin-target':'imageBox' }) %>
                                    <% end %>
                                    <%= ff.file_field :image, type: "file", id: "theory_point_image_uploads_#{index}", accept: ".png, .jpeq, .jpg, .webP", direct_upload: true,
                                            class: "image_fill hidden", data: { 'action': 'change->admin#display_image', 'admin-target':'imageInput' } %>
                                </label>
                            </div>
                        </div>
                    </div>  
                <% end %>
            <% end %>
        <% end %>
        <hr class="bg-slate-300 border-slate-300">
            <%= turbo_frame_tag "new_alternative", target: "_top" %>           
        <hr class="bg-slate-300 border-slate-300">
        <div class="flex flex-1 flex-col items-center bg-[#F7FCFC] py-6 list-holder">
                <div class="text-2xl text-center">
                    Exercises
                </div>
                <ol class="pl-4 pt-4 flex flex-col items-center list-decimal text-md text-center w-full key-points" data-admin-target="summarySourcesInput">
                    <% if (@page.exercises.empty?) %>
                            <%= f.hidden_field :exercises, value: '[]' %>
                            <li class="mb-1 w-full"><input class="page_exercise border-none w-[80%] bg-transparent" type="text" name="lesson_page[exercise]" value="" ></li>
                    <% else %>
                        <%= f.hidden_field :exercises, value: @page.exercises.to_json %>
                        <% @page.exercises.each do |exercise| %>
                            <li class="mb-1 w-full">
                                <input class="page_exercise border-none w-[80%] bg-transparent" type="text" name="lesson_page[exercise]" value="<%= exercise %>" >
                                <span class="cross" data-action="click->admin#remove_bullet">&#9587;</span>
                            </li>
                        <% end %>
                    <% end %>
                </ol>
                <%= f.text_area :key_point, class: "mt-2 max-w-[85%] flex summary_key_point flex-1 pl-4 w-full
                        border border-solid focus:border-blue-900 rounded", data: { "admin-target":"newSummaryKeyPoint" }, rows: 3 %>
                <div class="flex self-end pr-12">
                    <div data-action="click->admin#update_bullet_points" class="w-fit btn-blue
                            font-light px-2 py-2 border-black text-sm rounded mt-4 hover:cursor-pointer align-end">
                        Update Sources
                    </div>
                    <div data-action="click->admin#add_bullet_point" class="h-fit ml-2 w-fit btn-blue
                            font-light px-2 py-2 border-black text-sm rounded mt-4 hover:cursor-pointer">
                        + Add Sources
                    </div>
                </div>
        </div>
        <div class="py-6 flex-1 flex flex-col bg-white list-holder items-center">
            <div class="text-2xl text-center">
                Answers:
            </div>
            <ol class="pl-4 pt-4 flex flex-col items-center list-decimal text-md text-center w-full key-points">
                <% if (@page.answers.empty?) %>
                        <%= f.hidden_field :answers, value: '[]' %>
                        <li class="mb-1 w-full"><input class="page_answer border-none w-[80%] bg-transparent" type="text" name="lesson_page[answer]" value="" ></li>
                <% else %>
                    <%= f.hidden_field :answers, value: @page.answers.to_json %>
                    <% @page.answers.each do |answer| %>
                        <li class="mb-1 w-full">
                            <input class="page_answer border-none w-[80%] bg-transparent" type="text" name="lesson_page[answer]" value="<%= answer %>" >
                            <span class="cross" data-action="click->admin#remove_bullet">&#9587;</span>
                        </li>
                    <% end %>
                <% end %>
            </ol>
            <%= f.text_area :key_point, class: "mt-2 max-w-[85%] flex summary_key_point flex-1 pl-4 w-full
            border border-solid focus:border-blue-900 rounded", data: { "admin-target":"newSummaryKeyPoint" }, rows: 3 %>
            <div class="flex self-end pr-12">
                <div data-action="click->admin#update_bullet_points" class="w-fit btn-blue
                        font-light px-2 py-2 border-black text-sm rounded mt-4 hover:cursor-pointer align-end">
                    Update Sources
                </div>
                <div data-action="click->admin#add_bullet_point" class="h-fit ml-2 w-fit btn-blue
                        font-light px-2 py-2 border-black text-sm rounded mt-4 hover:cursor-pointer">
                    + Add Sources
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/admin/lesson_pages/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::LessonPages#update</h1>
  <p>Find me in app/views/admin/lesson_pages/update.html.erb</p>
</div>